"use client"
import * as React from "react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table"
import { useAuth } from "@/lib/auth"

const API="/admin/primeflow-1h-reports"
type Schedule={id:string;name:string;report_type:string;report_slot:string|null;execution_time:string;timezone:string;weekdays:number[];is_active:boolean;backfill_enabled:boolean;grace_period_minutes:number;retry_count:number;retry_delays_seconds:number[];sort_order:number;version:number;next_runs:string[]}
type Recipient={id:string;email:string;recipient_type:string;is_active:boolean}
type Run={id:string;report_date:string;trigger_type:string;status:string;subject:string;attempt_count:number;error_message?:string|null}
export function RlzReportManagement(){const{apiFetch}=useAuth();const[overview,setOverview]=React.useState<{schedules:Schedule[];recipients:Recipient[];recent_runs:Run[]}|null>(null);const[date,setDate]=React.useState(new Date().toISOString().slice(0,10));const[preview,setPreview]=React.useState<{html:string;report:{summary:Record<string,number>}}|null>(null);const[reason,setReason]=React.useState("");const[email,setEmail]=React.useState("");const[busy,setBusy]=React.useState(false)
const load=React.useCallback(async()=>{const r=await apiFetch(`${API}/rlz/overview`);if(r.ok)setOverview(await r.json());else toast.error("RLZ report management could not be loaded")},[apiFetch]);React.useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
const previewNow=async()=>{setBusy(true);const r=await apiFetch(`${API}/rlz/preview`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({report_date:date,use_default_recipients:true,to:[],cc:[],bcc:[]})});if(r.ok)setPreview(await r.json());else toast.error("Preview failed",{description:await r.text()});setBusy(false)}
const send=async()=>{setBusy(true);const r=await apiFetch(`${API}/rlz/send`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({report_date:date,use_default_recipients:true,to:[],cc:[],bcc:[],reason})});if(r.ok){toast.success("RLZ Daily Control sent");setReason("");await load()}else toast.error("Send failed",{description:await r.text()});setBusy(false)}
const addRecipient=async()=>{const r=await apiFetch(`${API}/recipients`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,report_type:"RLZ_DAILY_CONTROL",recipient_type:"TO",is_active:true,sort_order:(overview?.recipients.length||0)*10+10})});if(r.ok){setEmail("");await load()}else toast.error("Recipient could not be added",{description:await r.text()})}
const toggleSchedule=async(s:Schedule)=>{const r=await apiFetch(`${API}/schedules/${s.id}/${s.is_active?"disable":"enable"}`,{method:"POST"});if(r.ok)await load();else toast.error("Schedule update failed",{description:await r.text()})}
const updateTime=async(s:Schedule,value:string)=>{const body={name:s.name,report_type:s.report_type,report_slot:null,execution_time:value,timezone:s.timezone,weekdays:s.weekdays,is_active:s.is_active,backfill_enabled:false,predecessor_schedule_id:null,grace_period_minutes:s.grace_period_minutes,retry_count:s.retry_count,retry_delays_seconds:s.retry_delays_seconds,sort_order:s.sort_order};const r=await apiFetch(`${API}/schedules/${s.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(r.ok){toast.success("Schedule saved; hot reload within 45 seconds");await load()}else toast.error("Schedule update failed",{description:await r.text()})}
return <div className="space-y-5 rounded-xl border p-5"><div><h2 className="font-semibold">RLZ Daily Control</h2><p className="text-sm text-muted-foreground">Database-managed schedule, recipients, fresh preview, manual send and immutable run history.</p></div>
<div className="grid gap-4 lg:grid-cols-2"><div className="space-y-3 rounded-lg border p-4"><h3 className="font-medium">Preview / manual send</h3><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/><Button onClick={()=>void previewNow()} disabled={busy}>Preview fresh</Button>{preview&&<><div className="grid grid-cols-2 gap-2 text-xs">{Object.entries(preview.report.summary).map(([k,v])=><div key={k}>{k.replaceAll("_"," ")}: <b>{v}</b></div>)}</div><iframe title="RLZ email preview" srcDoc={preview.html} className="h-72 w-full rounded border"/><Input placeholder="Reason for manual send" value={reason} onChange={e=>setReason(e.target.value)}/><Button onClick={()=>void send()} disabled={busy||reason.trim().length<3}>Confirm and send</Button></>}</div>
<div className="space-y-3 rounded-lg border p-4"><h3 className="font-medium">Recipients</h3><div className="flex gap-2"><Input type="email" placeholder="actual@email.example" value={email} onChange={e=>setEmail(e.target.value)}/><Button onClick={()=>void addRecipient()} disabled={!email}>Add</Button></div>{overview?.recipients.map(r=><div key={r.id} className="flex justify-between rounded border p-2 text-sm"><span>{r.recipient_type} · {r.email}</span><span>{r.is_active?"Active":"Inactive"}</span></div>)}{!overview?.recipients.length&&<p className="text-sm text-amber-700">No recipient configured. Scheduled sends fail visibly until a valid address is added.</p>}</div></div>
<div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow>{["Schedule","Time","Weekdays","Timezone","State","Next run","Version","Action"].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{overview?.schedules.map(s=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell><Input type="time" defaultValue={s.execution_time} className="w-28" onBlur={e=>{if(e.currentTarget.value!==s.execution_time)void updateTime(s,e.currentTarget.value)}}/></TableCell><TableCell>{s.weekdays.join(",")}</TableCell><TableCell>{s.timezone}</TableCell><TableCell>{s.is_active?"Active":"Inactive"}</TableCell><TableCell>{s.next_runs?.[0]?.slice(0,16)||"—"}</TableCell><TableCell>v{s.version}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>void toggleSchedule(s)}>{s.is_active?"Disable":"Enable"}</Button></TableCell></TableRow>)}</TableBody></Table></div>
<div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow>{["Date","Trigger","Status","Subject","Attempts","Error"].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{overview?.recent_runs.map(r=><TableRow key={r.id}><TableCell>{r.report_date}</TableCell><TableCell>{r.trigger_type}</TableCell><TableCell>{r.status}</TableCell><TableCell>{r.subject}</TableCell><TableCell>{r.attempt_count}</TableCell><TableCell>{r.error_message||"—"}</TableCell></TableRow>)}</TableBody></Table></div></div>}
