"""add isolated vs workflow items

Revision ID: isolated_vs_items
Revises: 0019_add_common_problems
Create Date: 2026-01-09 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'isolated_vs_items'
down_revision = '0019_add_common_problems'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vs_workflow_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('internal_notes', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), server_default='TODO', nullable=False),
    sa.Column('priority', sa.String(), server_default='NORMAL', nullable=False),
    sa.Column('show_after_minutes', sa.Integer(), nullable=False),
    sa.Column('show_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dependency_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_vs_workflow_items_assigned_to_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_vs_workflow_items_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vs_workflow_items'))
    )
    op.create_index(op.f('ix_vs_workflow_items_project_id'), 'vs_workflow_items', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vs_workflow_items_project_id'), table_name='vs_workflow_items')
    op.drop_table('vs_workflow_items')
    # ### end Alembic commands ###
